sudo: required
dist: trusty
language: node_js

env:
  matrix:
    - NODE_VERSION="4" NPM_VERSION="3"
    - NODE_VERSION="5" NPM_VERSION="3"
    - NODE_VERSION="5" NPM_VERSION="3"
    - NODE_VERSION="6" NPM_VERSION="3"
    - NODE_VERSION="6" NPM_VERSION="4"
    - NODE_VERSION="7" NPM_VERSION="3"
    - NODE_VERSION="7" NPM_VERSION="4"
    - NODE_VERSION="8" NPM_VERSION="5"

before_install:
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  - source ~/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm use $NODE_VERSION
  # Build Tools
  - npm install -g npm@$NPM_VERSION
before_script:
  - npm run clean
  - npm run build
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
#  - npm run test
  - npm run e2e
